server:
  port: 9031
spring:
  application:
    name: zuul-route
  rabbitmq:
    host: localhost
    port: 5672
    username: zkna
    password: jk
eureka:
  client:
    service-url:
      defaultZone: http://root:jk@peer1:9001/eureka/,http://root:jk@peer2:9002/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"  #因为springboot2.1必须加上,支持访问/actuator/hystrix.stream