server:
  port: 9071
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HyattJobs/fund-trace-config.git
          search-paths: zfig-profiles
          clone-on-start: true
eureka:
  client:
    enabled: false