server:
  port: 9041
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:jk@peer1:9001/eureka/,http://root:jk@peer2:9002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"  #因为springboot2.1必须加上,支持访问/actuator/hystrix.stream
spring:
  application:
    name: service-monitor
#    index: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: zkna
    password: jk
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
#turbine:
#  app-config: fund,zuul-route
#  cluster-name-expression: "'default'"